{% set name = "deepchem" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepchem/deepchem/archive/{{ version }}.tar.gz
  sha256: 2463a02773d6260e48bd4957616ebb3bc49562e1f18f8f6cbde74bf082ede0e6

build:
  noarch: python
  number: 0
  script: PBR_VERSION=${PKG_VERSION} && export PBR_VERSION && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.5,<3.8
    - pip
    - setuptools
    - pbr

  run:
    - python >=3.5,<3.8
    - joblib
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  requires:
    - rdkit
  imports:
    - deepchem
  commands:
    - python run_test.py

about:
  home: https://github.com/deepchem/deepchem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Democratizing Deep-Learning for Drug Discovery, Quantum Chemistry, Materials Science and Biology

extra:
  recipe-maintainers:
    - rbharath
    - simonbray
