{% set name = "deepchem" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepchem/deepchem/archive/{{ version }}.tar.gz
  sha256: c7cf3b674fc55c86408683eaa469150bcf2e9e98038e293d84a985c3fee219b9

build:
  noarch: python
  number: 1
  script: PBR_VERSION=${PKG_VERSION} && export PBR_VERSION && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pbr

  run:
    - python >={{ python_min }},<3.10
    - joblib
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  requires:
    - rdkit
    - python {{ python_min }}
  imports:
    - deepchem
  commands:
    - python run_test.py

about:
  home: https://github.com/deepchem/deepchem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Democratizing Deep-Learning for Drug Discovery, Quantum Chemistry, Materials Science and Biology

extra:
  recipe-maintainers:
    - rbharath
    - simonbray
